requires 'CHI';
requires 'Moo';
requires 'MooX::Singleton';
requires 'DateTime';
requires 'Path::Class';
requires 'File::HomeDir';
requires 'WWW::Mechanize::Cached';
requires 'DateTime::Format::Natural';
requires 'DateTime::TimeZone';
requires 'Data::Rmap';
requires 'HTML::FormatText';
requires 'aliased';
requires 'IPC::Run3';
requires 'URL::Normalize';
requires 'XML::Feed';
requires 'Data::ICal';
requires 'Data::ICal::DateTime';

requires 'Data::Printer';
